channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - pip:
    - scipy==1.12.0  
    - tqdm==4.66.4
    - tensorflow==2.16.1
    - tensorflow-datasets==4.9.4
    - tensorflow-probability==0.24.0
    - https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.19+cuda11.cudnn86-cp312-cp312-manylinux2014_x86_64.whl
    - jax==0.4.19
    - xlrd==2.0.1
    - openpyxl==3.1.2
    - matplotlib==3.9.0
    - mlflow 
    - azure-ai-ml 
    - azureml-mlflow 
    - azureml-fsspec 
    - SGMCMCJax==0.2.13
    - einops==0.8.0
    - ott-jax==0.4.6
    - blackjax==1.1.1
    - jax-sgmc==0.1.4
    - seaborn==0.13.2
    - scikit-learn==1.5.0
    - arviz==0.18.0
    - sympy==1.12
    - neural_tangents==0.6.5
    - numpyro==0.15.0
    - retry==0.9.2
    - dm-haiku==0.0.12
    - oryx==0.2.7
    - geopandas==1.0.1
    - geoplot==0.5.1
    - neural_tangents==0.6.5
    